### ISSUE TITLE
Presentation completed

### ISSUE THREAD

**Issue by hnarmstrong** [mtkfolger/NUSIC#20]
Complete the Presentation SlideShow

Harrison - Future Direction, Concepts-challenges
Robert- Concepts,
Michael - Elevator Pitch,

**Comment by mtkfolger** [comment]
Presentation can be found at: [https://docs.google.com/presentation/d/1sikonPKi8TKgdR2cj5a1boOWdqGdT9qx5SyZ2NrGhg8/edit#slide=id.p](url)
