### ISSUE TITLE
Create Modals the greets user

### ISSUE THREAD

**Issue by hnarmstrong** [mtkfolger/NUSIC#5]
As a user I want to be greeted by a modal that explains how the website works.

UserStory:
When I visit the page the modal is displayed.
When I view the modal it contains instruction on how to use the website and has two buttons to close the modal or close and don't show again.
If i click close the modal closes and I can interact with the website
If i click close and don't show again the modal doesn't reappear when I revisit the page

**Comment by mtkfolger** [comment]
We have agreed to change the way the modal will work - it is now a button users _can_ click in order to see the instructions, instead of a default that always opens when we open the page. This issue has been resolved and is now closed.
